# Generated by Django 2.2.12 on 2020-05-21 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='swiped',
            table='swiped',
        ),
    ]
