# Generated by Django 2.2.12 on 2020-05-19 23:24

from django.db import migrations, models
import libs.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dating_location', models.CharField(max_length=128, verbose_name='目标城市')),
                ('dating_gender', models.CharField(choices=[('男', '男'), ('女', '女')], max_length=8, verbose_name='匹配的性别')),
                ('min_distance', models.IntegerField(default=0, verbose_name='最小查找范围')),
                ('max_distance', models.IntegerField(default=50, verbose_name='最大查找范围')),
                ('min_dating_age', models.IntegerField(default=18, verbose_name='最小交友年龄')),
                ('max_dating_age', models.IntegerField(default=50, verbose_name='最大交友年龄')),
                ('vibration', models.BooleanField(default=True, verbose_name='开启震动')),
                ('only_matched', models.BooleanField(default=True, verbose_name='不让陌生人查看我的相册')),
                ('auto_play', models.BooleanField(default=True, verbose_name='自动播')),
            ],
            options={
                'db_table': 'profile',
            },
            bases=(models.Model, libs.mixins.ModelMixin),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phonenum', models.CharField(max_length=20, unique=True, verbose_name='手机号')),
                ('nickname', models.CharField(max_length=50, unique=True, verbose_name='昵称')),
                ('gender', models.CharField(choices=[('男', '男'), ('女', '女')], default='男', max_length=8, verbose_name='性别')),
                ('birth_year', models.IntegerField(default=2000, verbose_name='出生年')),
                ('birth_month', models.IntegerField(default=1, verbose_name='出生月')),
                ('birth_day', models.IntegerField(default=1, verbose_name='出生日')),
                ('avatar', models.CharField(default='http://qak32ffdx.bkt.clouddn.com/morentouxiang.jpg', max_length=1024, verbose_name='个人形象的URL')),
                ('location', models.CharField(default='北京', max_length=16, verbose_name='常居地')),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
