# Generated by Django 2.2.12 on 2020-05-11 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phonenum', models.CharField(max_length=20, unique=True, verbose_name='手机号')),
                ('nickname', models.CharField(max_length=50, unique=True, verbose_name='昵称')),
                ('sex', models.CharField(choices=[('男', '男'), ('女', '女')], max_length=8, verbose_name='性别')),
                ('birth_year', models.IntegerField(default=2000, verbose_name='出生年')),
                ('birth_month', models.IntegerField(default=1, verbose_name='出生月')),
                ('birth_day', models.IntegerField(default=1, verbose_name='出生日')),
                ('avatar', models.CharField(max_length=1024, null=True, verbose_name='个人形象的URL')),
                ('location', models.CharField(max_length=16, null=True, verbose_name='常居地')),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
