# Generated by Django 2.2.12 on 2020-05-21 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.CharField(default='bj', max_length=16, verbose_name='常居地'),
        ),
    ]
