# Generated by Django 2.2.12 on 2020-05-13 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.CharField(default=None, max_length=1024, verbose_name='个人形象的URL'),
        ),
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.CharField(default=None, max_length=16, verbose_name='常居地'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('男', '男'), ('女', '女')], default='男', max_length=8, verbose_name='性别'),
        ),
    ]
